USE $(database)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

print 'Creating Unique Keys on BaseClass'
--
ALTER TABLE [dbo].[BaseClass] ADD  CONSTRAINT [UK_BaseClass] UNIQUE NONCLUSTERED 
(
	[Guid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

print 'Creating Unique Keys on BaseClassPartitioned'
--
ALTER TABLE [dbo].[BaseClassPartitioned] ADD  CONSTRAINT [UK_BaseClassPartitioned] UNIQUE NONCLUSTERED 
(
	[Guid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

print 'Creating Unique Keys on Foo'
--
ALTER TABLE [dbo].[Foo] ADD  CONSTRAINT [UK_Foo] UNIQUE NONCLUSTERED 
(
	[Guid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

print 'Creating Unique Keys on FooPartitioned'
--
ALTER TABLE [dbo].[FooPartitioned] ADD  CONSTRAINT [UK_FooPartitioned] UNIQUE NONCLUSTERED 
(
	[Guid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
